Import `torch` library

In [1]:
import torch
torch.__version__

'2.4.0'

# Tensors

Read: https://pytorch.org/docs/stable/tensors.html

## Scalar

In [2]:
# Scalar (zero dimension tensor)
scalar = torch.tensor(544)

scalar

tensor(544)

In [3]:
# Check dimesion of a tensor
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

544

## Vector

In [5]:
vector = torch.tensor([5, 4])
vector

tensor([5, 4])

In [6]:
vector.ndim

1

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

## Matrix

In [8]:
matrix = torch.tensor([[5, 4],
                       [2, 5]])

matrix

tensor([[5, 4],
        [2, 5]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

## Tensor

In [11]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

## Random tensors

In [147]:
random_tensor = torch.rand(size=(3,))

random_tensor, random_tensor.dtype

(tensor([0.0309, 0.6851, 0.1420]), torch.float32)

## Zeros and ones

In [148]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [149]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range

In [158]:
zero_to_ten = torch.arange(0, 10, 1)

zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensors like

In [160]:
ten_zeros = torch.zeros_like(zero_to_ten)

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [163]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device='mps', # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float16, device(type='mps', index=0))

# Manipulating tensors

## Basic operations

In [165]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [166]:
tensor * 10

tensor([10, 20, 30])

In [169]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [170]:
tensor * tensor

tensor([1, 4, 9])

## Matrix multiplication

Use `torch.matmul()` or `@`

In [171]:
torch.matmul(tensor, tensor)

tensor(14)

In [172]:
tensor @ tensor

tensor(14)

## Transpose a matrix

In [177]:
tensor.T

tensor([1, 2, 3])

`torch.nn.Linear()`

In [182]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)


# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
