Import `torch` library

In [1]:
import torch
torch.__version__

'2.4.0'

# Tensors

Read: https://pytorch.org/docs/stable/tensors.html

## Scalar

In [2]:
# Scalar (zero dimension tensor)
scalar = torch.tensor(544)

scalar

tensor(544)

In [3]:
# Check dimesion of a tensor
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

544

## Vector

In [5]:
vector = torch.tensor([5, 4])
vector

tensor([5, 4])

In [6]:
vector.ndim

1

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

## Matrix

In [8]:
matrix = torch.tensor([[5, 4],
                       [2, 5]])

matrix

tensor([[5, 4],
        [2, 5]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

## Tensor

In [11]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

## Random tensors

In [14]:
random_tensor = torch.rand(size=(3,))

random_tensor, random_tensor.dtype

(tensor([0.6965, 0.3446, 0.8528]), torch.float32)

## Zeros and ones

In [15]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range

In [17]:
zero_to_ten = torch.arange(0, 10, 1)

zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensors like

In [18]:
ten_zeros = torch.zeros_like(zero_to_ten)

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [19]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device='mps', # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float16, device(type='mps', index=0))

# Manipulating tensors

## Basic operations

In [20]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [21]:
tensor * 10

tensor([10, 20, 30])

In [22]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [23]:
tensor * tensor

tensor([1, 4, 9])

## Matrix multiplication

Use `torch.matmul()` or `@`

In [24]:
torch.matmul(tensor, tensor)

tensor(14)

In [25]:
tensor @ tensor

tensor(14)

## Transpose a matrix

In [26]:
tensor.T

/var/folders/n3/gsp927h9315ds95n9pgjfkb80000gn/T/ipykernel_90970/2861277930.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3701.)
  tensor.T


tensor([1, 2, 3])

`torch.nn.Linear()`

In [27]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)


# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## Aggregation

In [28]:
x = torch.arange(0, 100, 1)

x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
# Min
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 99
Sum: 4950


In [30]:
# mean() requires tensors to be in torch.float32 or another specific datatype

x.type(torch.float32).mean()

tensor(49.5000)

## Positional min/max

Find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

In [31]:
tensor = torch.arange(10, 100, 10)

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Index where max value occurs: 8
Index where min value occurs: 0


## Reshaping, stacking, squeezing and unsqueezing

Deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [32]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

`torch.reshape(input, shape)` reshapes input to shape (if compatible), can also use `torch.Tensor.reshape()`.

In [33]:
x_reshaped = torch.reshape(x, (1, 7))

x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

`Tensor.view(shape)` returns a view of the original tensor in a different shape but shares the same data as the original tensor.

Changing the view of a tensor with `torch.view()` really only creates a new view of the same tensor. So changing the view changes the original tensor too.

In [34]:
z = x.view(1, 7)

z

tensor([[1., 2., 3., 4., 5., 6., 7.]])

`torch.stack(tensors, dim=0)` concatenates a sequence of tensors along a new dimension (`dim`), all tensors must be same size.

In [35]:
x_stacked = torch.stack([x, x, x, x], dim=0)

x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

`torch.squeeze(input)` squeezes input to remove all the dimenions with value 1.

In [36]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


`torch.permute(input, dims)` returns a view of the original `input` with its dimensions permuted (rearranged) to `dims`.

In [37]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

In [38]:
x = torch.arange(1, 10).reshape(1, 3, 3)

x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [39]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1
